[general]
command_symbol = "-"

[database]
host = "ameo.link"
username = "kouffee-bot"
password = "lolno"
database = "kouffee-bot"

[economy]
daily_claim_interval_seconds = 600
claim_amount = 5000
currency_name = "Miku Bucks"

[ships]
timing_multiplier = 1.0

[ships.resource_names]
tier1 = "Hydrogen"
tier2 = "Lithium"
tier3 = "Silicon"
special1 = "Plutonium"

[ships.ship_names]
ship1 = "Fighter"
ship2 = "Interceptor"
ship3 = "Frigate"
ship4 = "Carrier"
shipSpecial1 = "Dreadnaught"

[ships.tier_names]
0 = "Common"
1 = "Uncommon"
2 = "Unusual"
3 = "Rare"
4 = "Epic"
5 = "Legendary"

[ships.raid_location_names]
[ships.raid_location_names.0]
name = "Kasdard"
description = "A solar system that was once home to an expansive mining operation.  Now idle, it still holds considerable unexploited mineral riches."

[ships.raid_location_names.1]
name = "The Abyss"
description = "An uncharted expanse of starless space hundreds of light years across, obscured by dense clouds of dark gas and dust.  It is littered with the ruins of an ancient war that decimated dozens of worlds."

[ships.raid_location_names.2]
name = "Sacellum Tenebris"
description = "A religious site from a lost civilization.  Reachable only via a forgotten hyperspace corridor, it has remained untouched for eons."
